name: Release
on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Run unit tests
        run: make test

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          args: release -f .github/goreleaser.yaml --rm-dist
          distribution: goreleaser
          version: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
